---
title: "viz"
output:
  word_document:
    reference_docx: knitting/docx_template.docx
  html_document: default
  pdf_document:
    latex_engine: xelatex
date: "2025-01-26"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(dpi=600)


packages = c("brms","tidyverse","bayesplot","pracma","here",
             "patchwork","posterior","HDInterval","loo", "furrr", "SBC","future","ggh4x")

do.call(pacman::p_load, as.list(packages))
```


# plot 1

```{r, fig.width = 7, fig.height = 5, warning = F, message = F, echo = F, dpi = 600}
source(here::here("Plots","Visualize_scripts.R"))
plot1 = plot_figure1(rerun = F, seed = 1997)

plot1
```

# plot 2

```{r, fig.width = 7, fig.height = 5, warning = F, message = F, echo = F, dpi = 600}
source(here::here("Plots","Visualize_scripts.R"))

plot2 = plot_figure2()

plot2

```


# plot 3

```{r, fig.width = 7, fig.height = 5, warning = F, message = F, echo = F, dpi = 600}
source(here::here("Plots","Visualize_scripts.R"))
plot3 = plot_figure3()

plot3
```


# plot 4

```{r, fig.width = 7, fig.height = 5, warning = F, message = F, echo = F, dpi = 600}
source(here::here("Plots","Visualize_scripts.R"))
plot4 = plot_figure4()

plot4
```




# plot 5

```{r, fig.width = 7, fig.height = 5, warning = F, message = F, echo = F, dpi = 600}
source(here::here("Plots","Visualize_scripts.R"))
plot5 = plot_figure5(rerun = F)

plot5
```





```{r, fig.height=5,fig.width=7.2}
# load("~/Modeling-the-experiment/real data/reinforcement learning/plotting.RData")
# load("~/Modeling-the-experiment/real data/Psychometric/plotting.RData")
# 
# 
# plot6 = ( (psycho_psycho / rts_psycho) | ( rw_rw / rts_rw) ) + 
#   plot_layout(guides = "collect") & 
#   theme(legend.position = "top")
# 
# 
# ggsave(here::here("Figures","plot6.tiff"),plot6, dpi = 600,
#        height = 5,width = 7.2)
# 
# plot6
```

